testing workflow

diff --git a/.github/workflows/main_hamburgers-calendar.yml b/.github/workflows/main_hamburgers-calendar.yml
--- a/.github/workflows/main_hamburgers-calendar.yml
+++ b/.github/workflows/main_hamburgers-calendar.yml
@@ -47,7 +47,13 @@ jobs:
           test -d packages/express-backend/node_modules/cors && echo "cors is installed ✅" || echo "cors is missing ❌"
           test -d packages/express-backend/node_modules/express && echo "express is installed ✅" || echo "express is missing ❌"
 
-        
+      #debug:
+      - name: install cors and test its prescence after explicit install
+        run: |
+          cd packages/express-backend
+          npm install cors
+          test -d packages/express-backend/node_modules/cors && echo "cors is installed ✅" || echo "cors is missing ❌"
+
       #debug
       - name: Check contents before upload
         run: ls -lh packages/express-backend/
